mode: development
media_root: media
media_url: /media
base_url: /
# If your site is nested inside of a bigger one, you can use media_url and
# base_url to properly generate links on your site. For example, if your URL
# will be some.domain.com/starter/, use:
#   media_url: /starter/media
#   base_url: /starter/
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    # Plugins needed for the advances section.
    - hyde.ext.plugins.meta.SorterPlugin
    - hyde.ext.plugins.meta.GrouperPlugin
    - hyde.ext.plugins.meta.TaggerPlugin
    - hyde.ext.plugins.text.SyntextPlugin
    - hyde.ext.plugins.text.TextlinksPlugin

context:
  data:
    site:
      name: My Web Site
      url:  http://localhost:8080
    menu:
      - title: Home
        url: /
      - title: About
      - url: /about.html
      
